Allow swift sdk to delete a wildcard
csync/csync-swift pull request #20
Opened 2017-02-02 15:56 UTC by boopt2

Resolves #19 
Proposed Changes:
*  Allow user to delete on wildcards
DCO1.1 Signed-off-by: Thomas Boop <tgboop@us.ibm.com>

2017-02-02 15:56 UTC, boopt2 commented
Hi boopt2,

Thanks for submitting this pull request!

I can confirm that the DCO1.1 sign-off has been included. It is okay to process this pull request.

dco-bot

2017-02-09 00:54 UTC, mkistler requested changes
Looks good.  Just needs a few small changes.

2017-02-09 00:54 UTC, mkistler commented on CSyncSDK/Operation.swift
> +			error = err(CSError.invalidKey, msg:"Only delete pubs may contain a wildcard")
I think this error message will be confusing to developers.  The developer does a "write", not a "pub", so a message about "delete pubs" won't help them.  I think you could leave the message as it is, but if you really feel it needs more detail, I would suggest "Key for write may not contain wildcard characters".

2017-02-09 00:54 UTC, mkistler commented on CSyncSDKTests/ListenTests.swift
> +	}
This test does not belong in the `ListenTests` file.  It should be in the `WriteTests` file -- all the other delete tests are in that file.

2017-02-09 18:02 UTC, mkistler approved these changes
Looks good! 👍

2017-02-09 18:28 UTC, merged